---
openapi: 3.0.0

tags:
  - name: Users
    description: Everything about Users

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all Users
      security:
        - bearerAuth: []
      responses:
        200:
          description: return list of all users
          content:
            application/json:
              schema:
                $ref: '#/components/responses/User'
    post:
      tags:
        - Users
      summary: Add a new user to the store
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              email: user@email.com
              password: password
      responses:
        200:
          description: return created user
          content:
            application/json:
              schema:
                $ref: '#/components/responses/User'
        400:
          $ref: '#/components/responses/BadRequest'
  /users/{userId}:
    get:
      tags:
        - Users
      summary: Get a user with a userId
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return a user
          content:
            application/json:
              schema:
                $ref: '#/components/responses/User'
        404:
          $ref: "#/components/responses/NotFound"
    put:
      tags:
        - Users
      summary: Update an existing user
      security:
        - bearerAuth: []
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          description: User ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              email: user@email.com
              password: password
      responses:
        200:
          description: Return updated user
          content:
            application/json:
              schema:
                $ref: '#/components/responses/User'            
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: "#/components/responses/NotFound"
    delete:
      tags:
        - Users
      summary: Delete an existing user
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
            $ref: "#/components/responses/NotFound"

components:
  responses:
    User:
      type: object
      properties:
        id: 
          type: string
        email:
          type: string
        createdOn:
          type: string
      example:
        id: 5c740a7de95c6ee5b1c00640
        email: "JohnDoe@email.com"
        createdOn: 2019-02-25 16:32:13.077
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - id
        - email
        - password
       
    